### ISSUE TITLE
how to modify posts quantity per page?

### ISSUE THREAD

**Issue by luckypoemster** [esaezgil/esaezgil.github.io#1]
hi.
i want to modify posts quantity per page to be 5,which file to modify?

**Comment by esaezgil** [comment]
hey @luckypoemster thanks for stopping by. As suggested in the [Hugo docs](https://gohugo.io/extras/pagination/) you can include the `Paginate` setting in you configuration (`config.toml`) which by default is set to 10. So just adding `Paginate=5` would set the number of post per page to 5.
In any case I am using the [beautifulhugo theme](https://github.com/halogenica/beautifulhugo/) where many other settings are configured. You can also check the [Hugo forum](https://discuss.gohugo.io/) for general questions on Hugo.
Cheers,
Enrique
